# Generated by Django 6.0.2 on 2026-02-24 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(help_text='Ej: alfajores, tortas-a-pedido', unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título interno (opcional)')),
                ('image', models.ImageField(upload_to='hero_gallery/', verbose_name='Imagen de Portada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Visible?')),
            ],
            options={
                'verbose_name': 'Imagen de Portada',
                'verbose_name_plural': 'Imágenes de Portada (Hero)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('client_name', models.CharField(help_text='Ej: Javiera, Hospital de Talca', max_length=100, verbose_name='Nombre/Tipo de Cliente')),
                ('text', models.TextField(verbose_name='Comentario del cliente')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Foto del producto o captura')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Visible?')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas de Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('min_order', models.CharField(blank=True, help_text='Ej: 20 unidades', max_length=100, verbose_name='Pedido Mínimo')),
                ('background_color', models.CharField(choices=[('bg-brand-cream', 'Crema (Clásico)'), ('bg-white', 'Blanco (Limpio)'), ('bg-brand-lightpurple', 'Lila Suave (Contraste)'), ('bg-brand-lila', 'Lila Fuerte (Acento)'), ('bg-[#efedea]', 'Gris Cálido (Minimalista)')], default='bg-brand-cream', help_text='Elige el color de fondo para la sección de este producto en la web.', max_length=50, verbose_name='Color de Fondo')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Visible?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_gallery/', verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Galería del Producto',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Pack 6 unidades', max_length=100, verbose_name='Nombre del Pack')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product')),
            ],
            options={
                'verbose_name': 'Pack/Precio',
                'verbose_name_plural': 'Packs y Precios',
                'ordering': ['price'],
            },
        ),
    ]
